# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a30ee93620415906bc535e577376bbec19ec3cbacfa8392fe3c0334ba35f94c7b0557cf16bb4aac06be026098eca51b1f09126b51dc2699ec74fd09a121d14d

test:
  secret_key_base: 1e987ac3fa803f6150e2f205d8f423c1bc1ac7cc47c9fe4fd6d7f8e209c85e4445fbbf276fe92908917145c93dd7cabfb2b243cebdb7c5bdcc8b28faa718b3aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
